//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PROV_CVV_PR
    {
        public int SourceID { get; set; }
        public string BASE_ID { get; set; }
        public string BIN { get; set; }
        public string BANK { get; set; }
        public string CARD_TYPE { get; set; }
        public string CARD_CLASS { get; set; }
        public string CARD_LEVEL { get; set; }
        public string CARD_EXP { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string DOB { get; set; }
        public string SSN { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string GENDER { get; set; }
        public string ADDR_LINE_1 { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PRICE { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual A_PROV_SRC A_PROV_SRC { get; set; }
    }
}
