//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PROV_BINLIST
    {
        public int iin_start { get; set; }
        public string iin_end { get; set; }
        public string number_length { get; set; }
        public string number_luhn { get; set; }
        public string scheme { get; set; }
        public string brand { get; set; }
        public string type { get; set; }
        public string prepaid { get; set; }
        public string country { get; set; }
        public string bank_name { get; set; }
        public string bank_logo { get; set; }
        public string bank_url { get; set; }
        public string bank_phone { get; set; }
        public string bank_city { get; set; }
    }
}
