//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDGColumnMapping
    {
        public int LDGColumnMappingId { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string TempTableColumnName { get; set; }
        public string OriginalTableColumnName { get; set; }
        public string ColumnDataType { get; set; }
        public Nullable<bool> IsCardData { get; set; }
    
        public virtual A_PROV_SRC A_PROV_SRC { get; set; }
    }
}
