//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MindWiseEntities : DbContext
    {
        public MindWiseEntities()
            : base("name=MindWiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_PROV_BINLIST> A_PROV_BINLIST { get; set; }
        public virtual DbSet<A_PROV_CLIENT> A_PROV_CLIENT { get; set; }
        public virtual DbSet<A_PROV_CVV_LDG> A_PROV_CVV_LDG { get; set; }
        public virtual DbSet<A_PROV_CVV_PR> A_PROV_CVV_PR { get; set; }
        public virtual DbSet<A_PROV_DUMPS_LDG> A_PROV_DUMPS_LDG { get; set; }
        public virtual DbSet<A_PROV_DUMPS_PR> A_PROV_DUMPS_PR { get; set; }
        public virtual DbSet<A_PROV_SRC> A_PROV_SRC { get; set; }
        public virtual DbSet<A_PROV_USERS> A_PROV_USERS { get; set; }
        public virtual DbSet<LDGColumnMapping> LDGColumnMappings { get; set; }
    }
}
