//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MindWiseEntities : DbContext
    {
        public MindWiseEntities()
            : base("name=MindWiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_PROV_BINLIST> A_PROV_BINLIST { get; set; }
        public virtual DbSet<A_PROV_CLIENT> A_PROV_CLIENT { get; set; }
        public virtual DbSet<A_PROV_CVV_LDG> A_PROV_CVV_LDG { get; set; }
        public virtual DbSet<A_PROV_CVV_PR> A_PROV_CVV_PR { get; set; }
        public virtual DbSet<A_PROV_DUMPS_LDG> A_PROV_DUMPS_LDG { get; set; }
        public virtual DbSet<A_PROV_DUMPS_PR> A_PROV_DUMPS_PR { get; set; }
        public virtual DbSet<A_PROV_SRC> A_PROV_SRC { get; set; }
        public virtual DbSet<A_PROV_USERS> A_PROV_USERS { get; set; }
        public virtual DbSet<LDGColumnMapping> LDGColumnMappings { get; set; }
    
        public virtual ObjectResult<GetCardClass_Result> GetCardClass(Nullable<int> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCardClass_Result>("GetCardClass", clientIdParameter);
        }
    
        public virtual ObjectResult<GetCVVLDG_Result> GetCVVLDG(Nullable<int> clientId, string serchBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var serchByParameter = serchBy != null ?
                new ObjectParameter("SerchBy", serchBy) :
                new ObjectParameter("SerchBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCVVLDG_Result>("GetCVVLDG", clientIdParameter, serchByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<GetDUMPSLDG_Result> GetDUMPSLDG(Nullable<int> clientId, string searchBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("SearchBy", searchBy) :
                new ObjectParameter("SearchBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDUMPSLDG_Result>("GetDUMPSLDG", clientIdParameter, searchByParameter, pageIndexParameter, pageSizeParameter);
        }
    }
}
